"use client";

import { useMemo, useState } from "react";
import { TEMPLATES, defaultParams, ladderRungs } from "@calibrate/backtest/templates";
import type { TemplateId } from "@calibrate/backtest/types";
import { NETWORKS } from "@calibrate/shared";
import { Card, H1, Note } from "./ui";

interface Series { asset: string; intervalSec: number }

/**
 * Maps a Calibrate template onto the closest Bot Kit strategy and renders its .env.
 * Only parameters with a documented Bot Kit counterpart (strategies/<name>/README.md
 * config tables, verified 2026-09-03) are mapped; the rest are listed as "not mapped".
 */
function botKitEnv(asset: string, template: TemplateId, p: Record<string, number>, network: "testnet" | "mainnet") {
  const net = NETWORKS[network];
  const common = [
    `# Generated by Calibrate — ${TEMPLATES[template].name} on ${asset}`,
    `# Apply as process environment for https://github.com/somnia-chain/dreamdex-bot-kit (Railway variables, or set -a; source this file; set +a)`,
    `NETWORK=${network}`,
    `DEPLOY_ENV=${network}`,
    `VENUE_ID=${net.defaultVenueId}`,
    `EC_UNDERLYING=${asset}`,
    `DRY_RUN=true   # flip to false only after a dry run looks right`,
    `# PRIVATE_KEY=0x...   # your own funded key; never paste a Calibrate burner here`,
  ];
  if (template === "ladder") {
    const rungs = ladderRungs(p);
    const spacing = rungs.length > 1 ? (rungs[rungs.length - 1]! - rungs[0]!) / (rungs.length - 1) : 0.05;
    const center = (rungs[0]! + rungs[rungs.length - 1]!) / 2;
    return {
      strategy: "ec-laddering-bot",
      env: [...common, `STRATEGY=ec-laddering-bot`, `GRID_LEVELS=${rungs.length}`, `GRID_SPACING=${spacing.toFixed(3)}`, `GRID_SIZE=${p.size_per_rung}`, `GRID_CENTER=${center.toFixed(3)}`].join("\n"),
      mapped: [["rungs", "GRID_LEVELS"], ["low_price/high_price", "GRID_SPACING and GRID_CENTER"], ["size_per_rung", "GRID_SIZE"]],
      unmapped: [["side_up", "ec-laddering-bot quotes both sides around GRID_CENTER"], ["delay_sec", "no equivalent; the bot quotes from window open"]],
    };
  }
  if (template === "momentum") {
    return {
      strategy: "ec-oracle-follow",
      env: [...common, `STRATEGY=ec-oracle-follow`, `OF_MODEL=momentum`, `OF_MOMENTUM_THRESHOLD=${(p.move_bps! / 10_000).toFixed(6)}`, `OF_MAX_SHARES=${p.size}`, `OF_NEAR_EXPIRY_STOP_MS=${Math.max(5, Math.round((p.seconds_left ?? 60) / 2)) * 1000}`, network === "mainnet" ? `PRICE_FEED_URL=   # required on mainnet: ec-oracle-follow needs an underlying price feed` : `# PRICE_FEED_URL bundled on testnet`].join("\n"),
      mapped: [["move_bps", "OF_MOMENTUM_THRESHOLD (as a fraction)"], ["size", "OF_MAX_SHARES"], ["seconds_left", "OF_NEAR_EXPIRY_STOP_MS (half of seconds_left; the bot stops taking, it does not time a single take)"]],
      unmapped: [["max_price / slippage_ticks / stale_sec", "the bot crosses the best ask when its model edge exceeds OF_EDGE (default 0.03)"]],
    };
  }
  return {
    strategy: "none",
    env: [...common, `# Late-window mispricing has no Bot Kit counterpart: it needs the calibration table.`, `# Run Calibrate's own runner instead (testnet only):`, `# STRATEGY_JSON='${JSON.stringify({ asset, intervalSec: 300, template, params: p })}' DRY_RUN=true npx tsx services/runner/src/runner.ts`].join("\n"),
    mapped: [],
    unmapped: [["all", "no Bot Kit strategy reads a calibration table"]],
  };
}

export function ExportStudio({ series, initial }: { series: Series[]; initial: { asset: string; template: TemplateId; params: Record<string, number> } }) {
  const [asset, setAsset] = useState(initial.asset);
  const [template, setTemplate] = useState<TemplateId>(initial.template);
  const [params, setParams] = useState<Record<string, number>>({ ...defaultParams(initial.template), ...initial.params });
  const [network, setNetwork] = useState<"testnet" | "mainnet">("mainnet");
  const out = useMemo(() => botKitEnv(asset, template, params, network), [asset, template, params, network]);
  const spec = TEMPLATES[template];
  const copy = () => navigator.clipboard?.writeText(out.env).catch(() => {});
  return (
    <>
      <H1 sub="Turn a tuned strategy into a Bot Kit configuration you run yourself, with your own key. Calibrate never hosts mainnet bots.">Export</H1>
      <div className="grid gap-6 lg:grid-cols-[340px_1fr]">
        <Card>
          <div className="mb-2 text-xs font-medium uppercase tracking-wider text-muted">Strategy</div>
          <div className="flex flex-wrap gap-1.5">
            {[...new Set(series.map((s) => s.asset))].map((a) => (
              <button key={a} onClick={() => setAsset(a)} className={`rounded-md border px-2.5 py-1 font-mono text-xs ${a === asset ? "border-accent bg-accent-soft text-accent" : "border-line text-muted"}`}>{a}</button>
            ))}
          </div>
          <select value={template} onChange={(e) => { const id = e.target.value as TemplateId; setTemplate(id); setParams(defaultParams(id)); }} className="mt-3 w-full rounded-md border border-line bg-surface px-2 py-1.5 text-sm">
            {(Object.keys(TEMPLATES) as TemplateId[]).map((id) => <option key={id} value={id}>{TEMPLATES[id].name}</option>)}
          </select>
          <div className="mt-3 flex flex-col gap-2">
            {spec.params.map((p) => (
              <label key={p.key} className="flex items-center gap-2 text-xs">
                <span className="w-40 shrink-0 text-muted">{p.label}</span>
                <input type="number" min={p.min} max={p.max} step={p.step} value={params[p.key] ?? p.default} onChange={(e) => setParams((prev) => ({ ...prev, [p.key]: Number(e.target.value) }))} className="w-24 rounded-md border border-line bg-surface px-2 py-1 font-mono" />
              </label>
            ))}
          </div>
          <div className="mt-3 flex gap-2 text-sm">
            {(["mainnet", "testnet"] as const).map((n) => (
              <button key={n} onClick={() => setNetwork(n)} className={`rounded-md border px-3 py-1 ${n === network ? "border-accent bg-accent-soft text-accent" : "border-line text-muted"}`}>{n}</button>
            ))}
          </div>
        </Card>
        <div className="flex flex-col gap-4">
          <Card>
            <div className="mb-2 flex items-center justify-between">
              <div className="text-xs font-medium uppercase tracking-wider text-muted">Bot Kit strategy: <span className="font-mono normal-case text-ink">{out.strategy}</span></div>
              <button onClick={copy} className="rounded-md border border-line px-3 py-1 text-xs">Copy</button>
            </div>
            <pre className="overflow-x-auto rounded-md bg-ground p-3 font-mono text-xs leading-relaxed">{out.env}</pre>
            <p className="mt-2 text-xs text-muted">Apply these as process environment variables (Railway variables, or <code className="font-mono">set -a; source .env; set +a</code> in a shell), then <code className="font-mono">npm start -w {out.strategy}</code>. The Bot Kit strategies read their own <code className="font-mono">OF_*</code>/<code className="font-mono">GRID_*</code>/<code className="font-mono">EC_UNDERLYING</code> variables at import time, before ec-core loads a <code className="font-mono">.env</code> file, so a bare <code className="font-mono">.env</code> only carries the network, venue and key.</p>
          </Card>
          <Card>
            <div className="mb-2 text-xs font-medium uppercase tracking-wider text-muted">Parameter mapping</div>
            <table className="w-full text-xs">
              <tbody className="font-mono">
                {out.mapped.map(([a, b]) => <tr key={a} className="border-t border-line"><td className="py-1 pr-3 text-up">{a}</td><td className="py-1 font-sans text-muted">→ {b}</td></tr>)}
                {out.unmapped.map(([a, b]) => <tr key={a} className="border-t border-line"><td className="py-1 pr-3 text-down">{a}</td><td className="py-1 font-sans text-muted">not mapped: {b}</td></tr>)}
              </tbody>
            </table>
          </Card>
          <Note>The Bot Kit strategies are different programs with their own signals. This export carries your sizing and thresholds across; it does not reproduce the backtest. Dry-run there first.</Note>
        </div>
      </div>
    </>
  );
}
